spring:
  profiles:
    active: dev
  application:
    name: cooperativa

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cooperativa
    username: root
    password: root

  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080